# Generated by Django 5.2.4 on 2025-07-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='Seat_number',
            new_name='seat_number',
        ),
        migrations.AddField(
            model_name='bus',
            name='no_of_seats',
            field=models.PositiveBigIntegerField(default=20),
            preserve_default=False,
        ),
    ]
