# Generated by Django 5.2.4 on 2025-07-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_alter_bus_reach_time_alter_bus_start_time_bookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='boking_time',
            new_name='booking_time',
        ),
    ]
